import { SkeletonAtom } from "../atoms/SkeletonAtom";

export const SkeletonStandings = () => {
    return (
        <div className="bg-[#1d2233]">
            <table className="w-full">
                <thead className="bg-[#111931]">
                    <tr>
                        <th className="w-11"></th>
                        <th>
                            <SkeletonAtom
                                variant={"text"}
                                width={35}
                                height={18}
                                backgroundColor={"#4b5563"}
                                borderRadius={""}
                            />
                        </th>
                        <th>
                            <SkeletonAtom
                                variant={"text"}
                                width={25}
                                height={18}
                                backgroundColor={"#4b5563"}
                                borderRadius={""}
                            />
                        </th>
                        <th>
                            <SkeletonAtom
                                variant={"text"}
                                width={25}
                                height={18}
                                backgroundColor={"#4b5563"}
                                borderRadius={""}
                            />
                        </th>
                        <th>
                            <SkeletonAtom
                                variant={"text"}
                                width={25}
                                height={18}
                                backgroundColor={"#4b5563"}
                                borderRadius={""}
                            />
                        </th>
                        <th>
                            <SkeletonAtom
                                variant={"text"}
                                width={25}
                                height={18}
                                backgroundColor={"#4b5563"}
                                borderRadius={""}
                            />
                        </th>
                        <th>
                            <SkeletonAtom
                                variant={"text"}
                                width={25}
                                height={18}
                                backgroundColor={"#4b5563"}
                                borderRadius={""}
                            />
                        </th>
                        <th>
                            <SkeletonAtom
                                variant={"text"}
                                width={25}
                                height={18}
                                backgroundColor={"#4b5563"}
                                borderRadius={""}
                            />
                        </th>
                        <th>
                            <SkeletonAtom
                                variant={"text"}
                                width={25}
                                height={18}
                                backgroundColor={"#4b5563"}
                                borderRadius={""}
                            />
                        </th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {Array(20)
                        .fill(null)
                        .map((_, index) => (
                            <tr
                                key={index}
                                className="border-b border-[#111931] text-center h-[3.4375rem]"
                            >
                                <td>
                                    <div className="mx-2">
                                        <SkeletonAtom
                                            variant={"text"}
                                            width={20}
                                            height={35}
                                            backgroundColor={"#4b5563"}
                                            borderRadius={""}
                                        />
                                    </div>
                                </td>
                                <td>
                                    <div className="lg:w-[9rem]">
                                        <SkeletonAtom
                                            variant={"text"}
                                            width={90}
                                            height={35}
                                            backgroundColor={"#4b5563"}
                                            borderRadius={""}
                                        />
                                    </div>
                                </td>
                                <td>
                                    <SkeletonAtom
                                        variant={"text"}
                                        width={25}
                                        height={35}
                                        backgroundColor={"#4b5563"}
                                        borderRadius={""}
                                    />
                                </td>
                                <td>
                                    <SkeletonAtom
                                        variant={"text"}
                                        width={25}
                                        height={35}
                                        backgroundColor={"#4b5563"}
                                        borderRadius={""}
                                    />
                                </td>
                                <td>
                                    <SkeletonAtom
                                        variant={"text"}
                                        width={25}
                                        height={35}
                                        backgroundColor={"#4b5563"}
                                        borderRadius={""}
                                    />
                                </td>
                                <td>
                                    <SkeletonAtom
                                        variant={"text"}
                                        width={25}
                                        height={35}
                                        backgroundColor={"#4b5563"}
                                        borderRadius={""}
                                    />
                                </td>
                                <td>
                                    <SkeletonAtom
                                        variant={"text"}
                                        width={25}
                                        height={35}
                                        backgroundColor={"#4b5563"}
                                        borderRadius={""}
                                    />
                                </td>
                                <td>
                                    <SkeletonAtom
                                        variant={"text"}
                                        width={25}
                                        height={35}
                                        backgroundColor={"#4b5563"}
                                        borderRadius={""}
                                    />
                                </td>
                                <td>
                                    <SkeletonAtom
                                        variant={"text"}
                                        width={25}
                                        height={35}
                                        backgroundColor={"#4b5563"}
                                        borderRadius={""}
                                    />
                                </td>
                                <td>
                                    <SkeletonAtom
                                        variant={"text"}
                                        width={15}
                                        height={35}
                                        backgroundColor={"#4b5563"}
                                        borderRadius={""}
                                    />
                                </td>
                            </tr>
                        ))}
                </tbody>
            </table>
        </div>
    );
};
