import { SkeletonAtom } from "../atoms/SkeletonAtom";

export const SkeletonTeamStatistics = () => {
    return (
        <div className="flex lg:space-x-3 flex-wrap justify-center flex-col lg:flex-row">
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
            <SkeletonAtom
                variant={"text"}
                width={195}
                height={182}
                backgroundColor={"#4b5563"}
                borderRadius={""}
            />
        </div>
    );
};
